apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    events {  }
    http {
        server {
            listen 80;
            location / {
                return 200 "Hello world!";
            }
        }
    }

